name: docs

on:
  # 每当 push 到 main 分支时触发部署
  push:
    branches: [main]
  # 手动触发部署
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          # “最近更新时间” 等 git 日志相关信息，需要拉取全部提交记录
          fetch-depth: 0

      # 部署到 Github Pages
      # 查看 workflow 的文档来获取更多信息
      # @see https://github.com/crazy-max/ghaction-github-pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: main
          build_dir: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 同步到 Gitee
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        with:
          source-repo: git@github.com:MillCloud/frontend-standard.git
          destination-repo: git@gitee.com:millcloud/frontend-standard.git
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}

      # 部署到 Gitee Pages
      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@main
        with:
          gitee-username: ModyQyW
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          gitee-repo: millcloud/frontend-standard
          branch: main
